SET IDENTITY_INSERT [dbo].[Toys] ON
INSERT INTO [dbo].[Toys] ([ToyId], [ToyName], [ToyManufacturer], [ToyColor], [ToyPrice], [AgeGroup]) VALUES (9, N'Car', N'P&G', N'Red', 500, N'12+')
INSERT INTO [dbo].[Toys] ([ToyId], [ToyName], [ToyManufacturer], [ToyColor], [ToyPrice], [AgeGroup]) VALUES (10, N'Car', N'P&G', N'Red', 500, N'12+')
INSERT INTO [dbo].[Toys] ([ToyId], [ToyName], [ToyManufacturer], [ToyColor], [ToyPrice], [AgeGroup]) VALUES (11, N'Racket', N'HQ Prison', N'Yellow', 750, N'10+')
INSERT INTO [dbo].[Toys] ([ToyId], [ToyName], [ToyManufacturer], [ToyColor], [ToyPrice], [AgeGroup]) VALUES (13, N'Bikram', N'Bikramjeet', N'Brown', 8384, N'21')
SET IDENTITY_INSERT [dbo].[Toys] OFF
